### ISSUE TITLE
No puedo instalar rails en mi PC

### ISSUE THREAD

**Issue by MartinLaspiur** [rails-es/rails-es.github.io#11]
C:\Sites>rails
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:318:in `to_specs': Co
uld not find 'railties' (>= 0) among 9 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=C:/Documents and Settings/xx/.gem/ruby/1.9.1;C:/Ruby193/lib
/ruby/gems/1.9.1', execute`gem env`for more information
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/dependency.rb:327:in`
to_spec'
        from C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_gem.rb
:64:in `gem'
        from C:/RailsInstaller/Ruby2.1.0/bin/rails:22:in`<main>'

**Comment by oinak** [comment]
Hola Martín

Este proyecto es para issues sobre la web http://rubyonrails.org.es

Trata de seguir las instrucciones de http://rubyonrails.org.es/instala.html y si aun así ves que no puedes, prueba a preguntar en https://groups.google.com/forum/#!forum/ror_es

Un saludo
