### ISSUE TITLE
Gema lanzada el 26 de Febrero 

### ISSUE THREAD

**Issue by jcardenasm** [rails-es/rails-es.github.io#12]
Traté de descargar la gema manualmente para actualizar el framework de Rails, pero no muestra el enlace de descarga. Pido su amable colaboración con el inconveniente.

**Comment by oinak** [comment]
Hola

Si quieres actualizar el rails de tu sistema antes de empezar una nueva app, ejecuta `gem update rails`

Si quieres hacer un cambio pequeño de versión en tu app rails, (ej: 4.2.3 a 4.2.5), actualiza la versión en el fichero `Gemfile` de tu aplicacion, y ejecuta `bundle update rails`

Si quieres hacer un cambio grande (ej Rails 4 a Rails 5) consulta una guía especifica tipo: http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html

Si estos comandos no te funcionan o tienes dudas sobre tu instalación de rails revisa http://rubyonrails.org.es/instala.html (Si algo está mal en esa página o no te funciona, avisanos)

Si necesitas ayuda más detallada quizá prefieras preguntar en https://groups.google.com/forum/#!forum/ror_es

Espero que te sirva de ayuda
