### ISSUE TITLE
Problemas en la instalacion de  BUNDLE INSTALLER

### ISSUE THREAD

**Issue by JoelCollao** [rails-es/rails-es.github.io#17]
![captura](https://cloud.githubusercontent.com/assets/23290339/20036259/e899db62-a3d1-11e6-98b3-809a0a5434d0.JPG)

**Comment by oinak** [comment]
Hola Joel, no estamos seguros de que intentas hacer.

Este proyecto de github y estas issues son de la _web_ de https://rubyonrails.org.es.

Si tienes dudas sobre el uso de Rails, más alla de lo que contamos en http://rubyonrails.org.es/instala.html, igual puedes probar a preguntar en https://groups.google.com/forum/#!forum/ror_es
